services:
  test-postgres:
    image: postgres:16-alpine
    container_name: fresco-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fresco_test
    ports:
      - '5433:5432'
    volumes:
      - fresco_postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  fresco_postgres_test_data:
