services:
  postgres-test:
    container_name: fresco-test-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - 5433:5432  # We keep the port mapping to avoid conflicts on the host
    environment:
      - POSTGRES_PASSWORD=test_postgres_password
      - POSTGRES_USER=test_user
      - POSTGRES_DB=test_db
    volumes:
      - test-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", '-U', 'test_user']
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - test-network

volumes:
  test-postgres:
    name: fresco-test-db-volume

networks:
  test-network:
    name: fresco-test-network