[build]
  command = "pnpm netlify-build"
  publish = ".next"

[template.environment]
  POSTGRES_PRISMA_UR = "Prisma URL"
  POSTGRES_URL_NON_POOLING = "URL NON POOLING"

[template]
  required-extensions = ["neon"]